export const configSelect = [
    {
        key:'option1',
        value:'软件'
    },{
        key:'option2',
        value:'国际'
    },{
        key:'option3',
        value:'自动化'
    },{
        key:'option4',
        value:'传媒'
    },{
        key:'option5',
        value:'体育'
    },{
        key:'option6',
        value:'先进'
    },{
        key:'option7',
        value:'经管/现邮'
    },{
        key:'option8',
        value:'理'
    },{
        key:'option9',
        value:'通信'
    },{
        key:'option10',
        value:'外国语'
    },{
        key:'option11',
        value:'计算机'
    },{
        key:'option12',
        value:'安法'
    },{
        key:'option13',
        value:'光电'
    },{
        key:'option14',
        value:'生信'
    },{
        key:'option15',
        value:'马克思'
    }
]
var newDate = new Date();
var str_date =
  newDate.getFullYear().toString().slice(2) +
  (newDate.getMonth() + 1).toString() +
  newDate.getDate().toString();
console.log(str_date);
export const configLid = [
    {
        key:'二教',
        value:'2J'+str_date
    },
    {
        key:'三教',
        value:'3J'+str_date
    },
    {
        key:'四教',
        value:'4J'+str_date
    },
    {
        key:'五教',
        value:'5J'+str_date
    },
    {
        key:'八教',
        value:'8J'+str_date
    },
    {
        key:'经管',
        value:'JG'+str_date
    },
    {
        key:'老图',
        value:'LT'+str_date
    },
    {
        key:'数图',
        value:'ST'+str_date
    },
    {
        key:'老操',
        value:'LC'+str_date
    },
    {
        key:'千喜鹤',
        value:'Q'+str_date
    },
    {
        key:'衍生',
        value:'Y'+str_date
    },
    {
        key:'中心食堂',
        value:'Z'+str_date
    },
    {
        key:'大西北食堂',
        value:'Z'+str_date
    },
    {
        key:'兴业苑',
        value:'X'+str_date
    },
    {
        key:'莘莘食堂',
        value:'SS'+str_date
    },
    {
        key:'樱花食堂',
        value:'YH'+str_date
    },
    {
        key:'保安亭',
        value:'Q'+str_date
    },
    {
        key:'二维码楼',
        valueL:'S'+str_date
    }
]
